### ISSUE TITLE
Export don´t work

### ISSUE THREAD

**Issue by Alvo-239** [fridgecow/smartalarm#22]
Hello, 
since 2nd October the export of the sleep data dosn´t work. It appears only a message "Error: null" or "Too many open files"
Version of this app is 1.8.1, Google Wear is 2.28.0.270002478.

**Comment by emberderek** [comment]
Hey,

I have same issue. Intresting, because if i installed app on my watch first time it was working for first 3 days. But from 4th day i got Error:null message uppon push the export button. I tryd reset my watch, reinstall all. But not helped. I think message depends on email addrass or somthing what didnt changing on reinstall.

I have app on 1.8.1 version too and Wear OS 2.31.0.284190117

Thx!

**Comment by Alvo-239** [comment]
Hello,
this issue is still active, it works for some times, now it doesn´t works now since 4.5.2020.

**Comment by kimmy917** [comment]
Same issue. Has anyone figured how to fix it

**Comment by fridgecow** [comment]
Hope is that https://github.com/fridgecow/smartalarm-server/commit/74818baffdf1cea43523e432666e8eed55efaab6 has fixed this.

**Comment by fridgecow** [comment]
Note that if you're having issues sending emails, you can always run https://github.com/fridgecow/smartalarm-server locally e.g on a home computer.
